fix

diff --git a/ubuntu b/ubuntu
--- a/ubuntu
+++ b/ubuntu
@@ -119,6 +119,10 @@ install_requirement(){
         libjpeg-dev libpng-dev libtiff-dev libgif-dev libwebp-dev imagemagick libpcre3 libpcre3-dev uuid-dev \
         gnupg2 ca-certificates lsb-release apache2-dev libxml2-dev libcurl4-openssl-dev liblmdb-dev libgeoip-dev pkgconf \
         libpcre++-dev libyajl-dev apt-utils htop nano supervisor bc libmaxminddb-dev libbrotli-dev -y
+    if [ $? -ne 0 ]; then
+        echo "requirement failed! Exiting..."
+        exit 1
+    fi
 
     service supervisor stop
     systemctl disable supervisor
